server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

tvMaze:
  url: https://api.tvmaze.com/shows

employee:
  url: http://localhost:8082


